FROM php:8.1-fpm

RUN apt-get update && apt-get install -y curl \
  && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get install -y nodejs zip unzip git

WORKDIR /app

COPY composer.json composer.lock ./
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --optimize-autoloader

COPY package*.json ./
RUN npm install

ENV PATH="./node_modules/.bin:$PATH"

COPY . .

RUN chmod +x ./node_modules/.bin/vite

RUN npm run build

EXPOSE 9000
CMD ["php-fpm"]
